# Generated by Django 5.0.7 on 2024-07-27 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("website", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="suppliers/")),
                (
                    "last_active",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
