# Generated by Django 5.0.7 on 2024-07-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('suppliers', '0002_alter_supplier_supplierdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128)),
                ('productDescription', models.TextField()),
                ('productImage', models.ImageField(upload_to='images/')),
                ('productPrice', models.FloatField()),
                ('productionDate', models.DateField()),
                ('expirationDate', models.DateField()),
                ('productStock', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
                ('productSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='suppliers.supplier')),
            ],
        ),
    ]
