# Generated by Django 5.0.7 on 2024-07-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('description', models.TextField()),
                ('stock_level', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('suppliers', models.ManyToManyField(to='suppliers.supplier')),
            ],
        ),
    ]
