# Generated by Django 5.0.7 on 2024-07-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='dafault.jpg', upload_to=''),
        ),
    ]
