# Generated by Django 5.0.7 on 2024-07-30 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_categoryimage'),
        ('products', '0001_initial'),
        ('suppliers', '0004_remove_supplier_productquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplierDiscount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='totalPriceOfunits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='unitPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='productStock',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='product',
            name='productSupplier',
        ),
        migrations.AddField(
            model_name='product',
            name='productSupplier',
            field=models.ManyToManyField(to='suppliers.supplier'),
        ),
    ]
