# Generated by Django 5.0.7 on 2024-07-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_categoryimage'),
        ('products', '0002_product_supplierdiscount_product_totalpriceofunits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
    ]
