# Generated by Django 5.0.7 on 2024-08-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productionDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplierDiscount',
        ),
    ]
