# Generated by Django 5.0.7 on 2024-08-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_productiondate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='totalPriceOfunits',
        ),
    ]
