# Generated by Django 5.0.6 on 2024-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="location",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.IntegerField(max_length=10),
        ),
    ]
