# Generated by Django 5.0.6 on 2024-07-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_supplier_location_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="images/default.jpg",
                null=True,
                upload_to="supplier_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
