# Generated by Django 5.0.7 on 2024-07-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
