# Generated by Django 5.0.7 on 2024-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
