# Generated by Django 5.0.7 on 2024-07-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_expiry_date_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default-product.jpg', upload_to='images/'),
        ),
    ]
