# Generated by Django 3.1.13 on 2024-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240727_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_logos/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
