# Generated by Django 3.1.13 on 2024-07-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240727_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
