# Generated by Django 5.0.7 on 2024-07-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_id_alter_product_id_alter_stock_id_and_more'),
        ('inventory', '0007_auto_20240729_0745'),
    ]

    operations = [
    ]
