# Generated by Django 5.0.6 on 2024-07-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Product', models.CharField(max_length=255)),
                ('Status_Product', models.BooleanField()),
                ('Quantity_Product', models.PositiveIntegerField()),
                ('Price_Product', models.FloatField()),
                ('Expiration_date', models.DateField(null=True)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Images_Product', models.ImageField(default='images_product/default.png', upload_to='images_Product/')),
                ('Description_product', models.TextField(null=True)),
                ('Category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('Supplier_product', models.ManyToManyField(to='Supplier.supplier')),
            ],
        ),
    ]
