# Generated by Django 5.0.6 on 2024-07-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Category.category'),
        ),
    ]
