# Generated by Django 5.0.7 on 2024-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_supplier_alter_product_category'),
        ('Supplier', '0002_supplier_description_alter_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(to='Supplier.supplier'),
        ),
    ]
