# Generated by Django 5.0.6 on 2024-07-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Notifications',
            field=models.BooleanField(default=False),
        ),
    ]
