# Generated by Django 5.0.7 on 2024-07-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_stock_update',
        ),
    ]
