# Generated by Django 4.2.13 on 2024-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_expirment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="expirment", field=models.DateField(null=True),
        ),
    ]
