# Generated by Django 4.2.13 on 2024-07-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
        ("products", "0003_alter_product_expirment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expirment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
    ]
