# Generated by Django 4.2.13 on 2024-07-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("suppliers", "0001_initial"),
        ("products", "0004_alter_product_expirment_alter_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
        migrations.RemoveField(model_name="product", name="supplier",),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ManyToManyField(null=True, to="suppliers.supplier"),
        ),
    ]
