# Generated by Django 4.2.13 on 2024-07-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_name"),
        ("products", "0005_alter_product_category_remove_product_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="product", name="expirment", field=models.DateField(null=True),
        ),
    ]
