# Generated by Django 4.2.13 on 2024-07-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
