# Generated by Django 4.2.13 on 2024-07-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="notifeied_exieration",
            field=models.BooleanField(default=False),
        ),
    ]
