# Generated by Django 5.0.7 on 2024-07-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
