# Generated by Django 5.0.7 on 2024-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierAddress', models.TextField()),
                ('supplierPhoneNumber', models.CharField(max_length=15)),
                ('supplierEmail', models.EmailField(max_length=254)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('productQuantity', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('supplierDiscount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
