# Generated by Django 5.0.7 on 2024-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplierDiscount',
            field=models.SmallIntegerField(),
        ),
    ]
