# Generated by Django 5.0.7 on 2024-07-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_supplierdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplierImage',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
