# Generated by Django 5.0.7 on 2024-07-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_supplierimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='productQuantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplierDiscount',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unitPrice',
        ),
    ]
