# Generated by Django 5.0.7 on 2024-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, default='images/default-supplier.png', upload_to='images/'),
        ),
    ]
