# Generated by Django 5.0.7 on 2024-07-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(default='www.warehouse.com'),
            preserve_default=False,
        ),
    ]
