# Generated by Django 5.0.6 on 2024-07-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='logo',
        ),
    ]
