# Generated by Django 5.0.6 on 2024-07-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
