# Generated by Django 4.2.13 on 2024-07-28 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
