# Generated by Django 4.2.13 on 2024-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        default="images/no-logo-png-6.png", upload_to="images/"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("phone", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
    ]
