# Generated by Django 5.0.7 on 2024-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
