# Generated by Django 5.0.7 on 2024-08-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_categoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryImage',
        ),
    ]
