# Generated by Django 5.0.6 on 2024-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Supplier', models.CharField(max_length=255)),
                ('logo_Supplier', models.ImageField(default='images/default.png', upload_to='images_supplier/')),
                ('email_supplier', models.EmailField(max_length=254)),
                ('number_phone', models.CharField(max_length=9)),
                ('address_Supplier', models.TextField(null=True)),
                ('website_Supplier', models.URLField(null=True)),
            ],
        ),
    ]
