# Generated by Django 5.0.7 on 2024-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
